# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tech Support App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for Tech Support App

  target 'Tech Support AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tech Support AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
